// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30GN2Dif5XOIANRWHKxzhXjEcWXrxBLo',
    appId: '1:803718791094:web:752f2d2ee43798a46d8b17',
    messagingSenderId: '803718791094',
    projectId: 'eraa-app-7ca6c',
    authDomain: 'eraa-app-7ca6c.firebaseapp.com',
    storageBucket: 'eraa-app-7ca6c.appspot.com',
    measurementId: 'G-30YE232GTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbI8pujBsSYAG1Tmu_AyB7UvNyM0W0Z9E',
    appId: '1:803718791094:android:94bd2b1f4a5c06af6d8b17',
    messagingSenderId: '803718791094',
    projectId: 'eraa-app-7ca6c',
    storageBucket: 'eraa-app-7ca6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2PVosnTc591Vr0bFNRN0dIEqy1xvy4Q',
    appId: '1:803718791094:ios:0bbc12ec4f4d5a506d8b17',
    messagingSenderId: '803718791094',
    projectId: 'eraa-app-7ca6c',
    storageBucket: 'eraa-app-7ca6c.appspot.com',
    androidClientId: '803718791094-74beruepqct3luj3a2p2tjotbe4sf2ik.apps.googleusercontent.com',
    iosClientId: '803718791094-005guiiijbtlm6euusob9tek4c8hid6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.eraaFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT2PVosnTc591Vr0bFNRN0dIEqy1xvy4Q',
    appId: '1:803718791094:ios:f0fdefb88a900e0d6d8b17',
    messagingSenderId: '803718791094',
    projectId: 'eraa-app-7ca6c',
    storageBucket: 'eraa-app-7ca6c.appspot.com',
    androidClientId: '803718791094-74beruepqct3luj3a2p2tjotbe4sf2ik.apps.googleusercontent.com',
    iosClientId: '803718791094-tg795q4i2hg0kqoq18gdlr66kbll5s6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.eraaFirebaseApp.RunnerTests',
  );
}
